/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyekakhir_powerrangers;


import javax.swing.JOptionPane; //Import ini digunakan untuk mengimpor kelas JOptionPane dari paket javax.swing
import java.sql.*; //Import ini digunakan untuk mengimpor semua kelas yang ada dalam paket java.sql

/**
 * Kelas Login digunakan untuk menampilkan form login.
 * Menghubungkan ke database dan melakukan proses autentikasi pengguna.
 * @author Isa Agiya
 */
public class Login extends javax.swing.JFrame {
    /**
     *  Membuat form login baru.
     *  Inisialisasi koneksi ke database.
     *  Membuat objek statement, result set.
     */
    Connection con = koneksi.bukaKoneksi(); //
    public Statement stm;
    public ResultSet rs;
    public Login() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblLoginL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfUsernameL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pfPasswordL = new javax.swing.JPasswordField();
        jBLoginL = new javax.swing.JButton();
        lblToRegistL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBshowPasswordL = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        lblCLoseL = new javax.swing.JLabel();
        lblMinimizeL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblWelcome.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 153, 153));
        lblWelcome.setText("WELCOME TO KASIRIN AJE");

        lblLoginL.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lblLoginL.setForeground(new java.awt.Color(0, 153, 153));
        lblLoginL.setText("LOGIN IN NOW!");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("enter your username:");

        tfUsernameL.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("enter your password:");

        pfPasswordL.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        jBLoginL.setBackground(new java.awt.Color(0, 102, 102));
        jBLoginL.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jBLoginL.setForeground(new java.awt.Color(0, 204, 204));
        jBLoginL.setText("LOGIN");
        jBLoginL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginLActionPerformed(evt);
            }
        });

        lblToRegistL.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblToRegistL.setForeground(new java.awt.Color(0, 153, 153));
        lblToRegistL.setText("Don't have an account? Regist now!");
        lblToRegistL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblToRegistLMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyekakhir_powerrangers/loginPng.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyekakhir_powerrangers/Kasirinpng.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jCBshowPasswordL.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jCBshowPasswordL.setForeground(new java.awt.Color(0, 153, 153));
        jCBshowPasswordL.setText("Show Password");
        jCBshowPasswordL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBshowPasswordLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblToRegistL)))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBshowPasswordL)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pfPasswordL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(tfUsernameL, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(lblLoginL)
                                    .addComponent(jLabel7)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jBLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoginL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfUsernameL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfPasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBshowPasswordL)
                .addGap(18, 18, 18)
                .addComponent(jBLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblToRegistL)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 470, 520));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblCLoseL.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lblCLoseL.setText("X");
        lblCLoseL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCLoseLMouseClicked(evt);
            }
        });

        lblMinimizeL.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lblMinimizeL.setText("-");
        lblMinimizeL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addComponent(lblMinimizeL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCLoseL)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCLoseL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblMinimizeL)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblToRegistLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblToRegistLMouseClicked
        // TODO add your handling code here:
        
        // Membuat objek Register
        Register rg = new Register();
        
        // Menampilkan form Register
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
        dispose(); // Hide the login page
    }//GEN-LAST:event_lblToRegistLMouseClicked

    private void lblCLoseLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCLoseLMouseClicked
        // TODO add your handling code here:
        //To close the window
        System.exit(0);
        
    }//GEN-LAST:event_lblCLoseLMouseClicked

    private void lblMinimizeLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeLMouseClicked
        // TODO add your handling code here:
        //To minimize the window
        this.setState(1);
    }//GEN-LAST:event_lblMinimizeLMouseClicked

    private void jBLoginLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginLActionPerformed
      // TODO add your handling code here:
     
         // Memeriksa apakah username dan password tidak kosong
        if (!tfUsernameL.getText().isEmpty() && !pfPasswordL.getText().isEmpty()) {
            try {
            // Query untuk memeriksa kecocokan username dan password di database
            String query = "SELECT * FROM dataregis WHERE username = ? AND password = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, tfUsernameL.getText());
            ps.setString(2, pfPasswordL.getText());
            ResultSet rs = ps.executeQuery();
            
            // Jika username dan password cocok
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Halo, " + tfUsernameL.getText(), "Message", JOptionPane.INFORMATION_MESSAGE);
                
                // Menutup halaman login
                this.dispose();
                
                // Menampilkan halaman TampilanAwal
                TampilanAwal tj = new TampilanAwal();
                tj.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Pastikan username dan password sudah benar.", "Login", JOptionPane.ERROR_MESSAGE);
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
            // Jika username dan password kosong
        }else if (tfUsernameL.getText().isEmpty() && pfPasswordL.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi data mu!", "Warning", JOptionPane.ERROR_MESSAGE);
            
            // Jika username kosong
        }else if (tfUsernameL.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Username belum diisi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                
                // Jika password kosong
        }else if(pfPasswordL.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Password belum diisi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBLoginLActionPerformed

    private void jCBshowPasswordLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBshowPasswordLActionPerformed
        // TODO add your handling code here:
        
        // Jika checkbox "Show Password" diaktifkan
        if(jCBshowPasswordL.isSelected()){
            // Mengatur karakter echo password menjadi 0 (menampilkan karakter asli)
            pfPasswordL.setEchoChar((char)0);
        }else{
            // Jika checkbox "Show Password" tidak diaktifkan
            // Mengatur karakter echo password menjadi '*' (menggantikan karakter asli dengan '*')
            pfPasswordL.setEchoChar('*');
        }
    }//GEN-LAST:event_jCBshowPasswordLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Membuat instance objek Login dan menampilkannya
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLoginL;
    private javax.swing.JCheckBox jCBshowPasswordL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCLoseL;
    private javax.swing.JLabel lblLoginL;
    private javax.swing.JLabel lblMinimizeL;
    private javax.swing.JLabel lblToRegistL;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPasswordField pfPasswordL;
    private javax.swing.JTextField tfUsernameL;
    // End of variables declaration//GEN-END:variables
}
