/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyekakhir_powerrangers;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Isa Agiya
 */
public class Register extends javax.swing.JFrame {
    Connection con = koneksi.bukaKoneksi();
    Statement stm;
    ResultSet rs;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfUsernameR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pfPasswordR = new javax.swing.JPasswordField();
        jbRegistR = new javax.swing.JButton();
        lblToLoginR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBShowPasswordR = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        lblCloseR = new javax.swing.JLabel();
        lblMinimizeR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblWelcome.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 153, 153));
        lblWelcome.setText("WELCOME TO KASIRIN AJE");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("REGISTER NOW!");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("enter your username:");

        tfUsernameR.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tfUsernameR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameRActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("enter your password:");

        pfPasswordR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jbRegistR.setBackground(new java.awt.Color(0, 102, 102));
        jbRegistR.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jbRegistR.setForeground(new java.awt.Color(0, 204, 204));
        jbRegistR.setText("REGIST");
        jbRegistR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistRActionPerformed(evt);
            }
        });

        lblToLoginR.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblToLoginR.setForeground(new java.awt.Color(0, 153, 153));
        lblToLoginR.setText("Already have an account?Login now!");
        lblToLoginR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblToLoginRMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyekakhir_powerrangers/Kasirinpng.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyekakhir_powerrangers/loginPng.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jCBShowPasswordR.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jCBShowPasswordR.setForeground(new java.awt.Color(0, 153, 153));
        jCBShowPasswordR.setText("Show Password");
        jCBShowPasswordR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBShowPasswordRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbRegistR, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblToLoginR)))
                        .addGap(143, 143, 143))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfPasswordR, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfUsernameR, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jCBShowPasswordR))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfUsernameR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfPasswordR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jCBShowPasswordR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbRegistR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblToLoginR)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 490, 530));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblCloseR.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lblCloseR.setText("X");
        lblCloseR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseRMouseClicked(evt);
            }
        });

        lblMinimizeR.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lblMinimizeR.setText("-");
        lblMinimizeR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeRMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 432, Short.MAX_VALUE)
                .addComponent(lblMinimizeR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCloseR)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCloseR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblMinimizeR)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseRMouseClicked
        // TODO add your handling code here:
        //To close the window
        System.exit(0);
    }//GEN-LAST:event_lblCloseRMouseClicked

    private void lblMinimizeRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeRMouseClicked
        // TODO add your handling code here:
         //To minimize the window
        this.setState(1);
    }//GEN-LAST:event_lblMinimizeRMouseClicked

    private void lblToLoginRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblToLoginRMouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
        dispose(); // Hide the register page
    }//GEN-LAST:event_lblToLoginRMouseClicked

    private void jbRegistRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistRActionPerformed
        // TODO add your handling code here:
       try {
    String username = tfUsernameR.getText();
    String password = pfPasswordR.getText();

    if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username harus diisi!!!");
    } else if (password.isEmpty() || password.length() < 10) {
        JOptionPane.showMessageDialog(this, "Password harus minimal panjang 10 karakter!!!");
    } else {
        stm = con.createStatement();
        rs = stm.executeQuery("select * from dataregis where username = '" + username + "'");
        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Username sudah ada", "Pesan", JOptionPane.ERROR_MESSAGE);
        } else {
            stm.executeUpdate("insert into dataregis values ('" + username + "', '" + password + "')");
            JOptionPane.showMessageDialog(this, "Selamat Bergabung di KasirinAje:D");

            // Perform page transition here
            Login lg = new Login();
            lg.setVisible(true);
            lg.pack();
            lg.setLocationRelativeTo(null);
            lg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
            this.dispose(); // Close the current frame
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Koneksi Gagal");
}
        
    }//GEN-LAST:event_jbRegistRActionPerformed

    private void tfUsernameRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameRActionPerformed

    private void jCBShowPasswordRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBShowPasswordRActionPerformed
        // TODO add your handling code here:
        if(jCBShowPasswordR.isSelected()){
            pfPasswordR.setEchoChar((char)0);
        }else{
            pfPasswordR.setEchoChar('*');
        }
    }//GEN-LAST:event_jCBShowPasswordRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCBShowPasswordR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbRegistR;
    private javax.swing.JLabel lblCloseR;
    private javax.swing.JLabel lblMinimizeR;
    private javax.swing.JLabel lblToLoginR;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPasswordField pfPasswordR;
    private javax.swing.JTextField tfUsernameR;
    // End of variables declaration//GEN-END:variables
}
